<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="21" total="24" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-09T15:20:01 CEST" name="Demo Suite" finished-at="2022-07-09T15:20:20 CEST" duration-ms="18816">
    <groups>
      <group name="regression">
        <method signature="SuccessfulLoginLogout.testSuccessfulLoinLogout()[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" name="testSuccessfulLoinLogout" class="tests.login.SuccessfulLoginLogout"/>
        <method signature="SuccessfulLoginLogoutTwoDrivers.testSuccessfulLoinLogoutTwoDrivers()[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2]" name="testSuccessfulLoinLogoutTwoDrivers" class="tests.login.SuccessfulLoginLogoutTwoDrivers"/>
        <method signature="UnsuccessfulLoginWrongPassword.UnsuccessfulLoginWrongPassword()[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691]" name="UnsuccessfulLoginWrongPassword" class="tests.login.UnsuccessfulLoginWrongPassword"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="SuccessfulLoginLogout.testSuccessfulLoinLogout()[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" name="testSuccessfulLoinLogout" class="tests.login.SuccessfulLoginLogout"/>
      </group> <!-- sanity -->
      <group name="login">
        <method signature="SuccessfulLoginLogout.testSuccessfulLoinLogout()[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" name="testSuccessfulLoinLogout" class="tests.login.SuccessfulLoginLogout"/>
        <method signature="SuccessfulLoginLogoutTwoDrivers.testSuccessfulLoinLogoutTwoDrivers()[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2]" name="testSuccessfulLoinLogoutTwoDrivers" class="tests.login.SuccessfulLoginLogoutTwoDrivers"/>
        <method signature="UnsuccessfulLoginWrongPassword.UnsuccessfulLoginWrongPassword()[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691]" name="UnsuccessfulLoginWrongPassword" class="tests.login.UnsuccessfulLoginWrongPassword"/>
      </group> <!-- login -->
      <group name="demo">
        <method signature="SuccessfulLoginLogout.testSuccessfulLoinLogout()[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" name="testSuccessfulLoinLogout" class="tests.login.SuccessfulLoginLogout"/>
        <method signature="SuccessfulLoginLogoutTwoDrivers.testSuccessfulLoinLogoutTwoDrivers()[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2]" name="testSuccessfulLoinLogoutTwoDrivers" class="tests.login.SuccessfulLoginLogoutTwoDrivers"/>
        <method signature="UnsuccessfulLoginWrongPassword.UnsuccessfulLoginWrongPassword()[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691]" name="UnsuccessfulLoginWrongPassword" class="tests.login.UnsuccessfulLoginWrongPassword"/>
      </group> <!-- demo -->
    </groups>
    <test started-at="2022-07-09T15:20:01 CEST" name="Demo Tests" finished-at="2022-07-09T15:20:20 CEST" duration-ms="18816">
      <class name="tests.login.SuccessfulLoginLogoutTwoDrivers">
        <test-method is-config="true" signature="setUpTest(org.testng.ITestContext)[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2]" started-at="2022-07-09T15:20:01 CEST" name="setUpTest" finished-at="2022-07-09T15:20:10 CEST" duration-ms="8633" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@70ab2d48]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testSuccessfulLoinLogoutTwoDrivers()[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2]" started-at="2022-07-09T15:20:10 CEST" name="testSuccessfulLoinLogoutTwoDrivers" finished-at="2022-07-09T15:20:17 CEST" duration-ms="7419" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Nema!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Nema!
at org.testng.Assert.fail(Assert.java:110)
at tests.login.SuccessfulLoginLogoutTwoDrivers.testSuccessfulLoinLogoutTwoDrivers(SuccessfulLoginLogoutTwoDrivers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessfulLoinLogoutTwoDrivers -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2]" started-at="2022-07-09T15:20:18 CEST" name="tearDown" finished-at="2022-07-09T15:20:20 CEST" duration-ms="2085" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testSuccessfulLoinLogoutTwoDrivers status=FAILURE method=SuccessfulLoginLogoutTwoDrivers.testSuccessfulLoinLogoutTwoDrivers()[pri:0, instance:tests.login.SuccessfulLoginLogoutTwoDrivers@5dd1c9f2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.login.SuccessfulLoginLogoutTwoDrivers -->
      <class name="tests.login.UnsuccessfulLoginWrongPassword">
        <test-method is-config="true" signature="setUpTest(org.testng.ITestContext)[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691]" started-at="2022-07-09T15:20:01 CEST" name="setUpTest" finished-at="2022-07-09T15:20:06 CEST" duration-ms="4403" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@70ab2d48]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="UnsuccessfulLoginWrongPassword()[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691]" started-at="2022-07-09T15:20:06 CEST" name="UnsuccessfulLoginWrongPassword" finished-at="2022-07-09T15:20:11 CEST" duration-ms="4749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UnsuccessfulLoginWrongPassword -->
        <test-method is-config="true" signature="tearDownTest(org.testng.ITestResult)[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691]" started-at="2022-07-09T15:20:11 CEST" name="tearDownTest" finished-at="2022-07-09T15:20:15 CEST" duration-ms="4121" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UnsuccessfulLoginWrongPassword status=SUCCESS method=UnsuccessfulLoginWrongPassword.UnsuccessfulLoginWrongPassword()[pri:0, instance:tests.login.UnsuccessfulLoginWrongPassword@59b38691] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
      </class> <!-- tests.login.UnsuccessfulLoginWrongPassword -->
      <class name="tests.login.SuccessfulLoginLogout">
        <test-method is-config="true" signature="setUpTest(org.testng.ITestContext)[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" started-at="2022-07-09T15:20:01 CEST" name="setUpTest" finished-at="2022-07-09T15:20:06 CEST" duration-ms="4443" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@70ab2d48]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="testSuccessfulLoinLogout()[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" started-at="2022-07-09T15:20:06 CEST" name="testSuccessfulLoinLogout" finished-at="2022-07-09T15:20:11 CEST" duration-ms="5491" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[PADANCIJA!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: PADANCIJA!!!
at org.testng.Assert.fail(Assert.java:110)
at tests.login.SuccessfulLoginLogout.testSuccessfulLoinLogout(SuccessfulLoginLogout.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessfulLoinLogout -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73]" started-at="2022-07-09T15:20:12 CEST" name="tearDown" finished-at="2022-07-09T15:20:15 CEST" duration-ms="2987" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testSuccessfulLoinLogout status=FAILURE method=SuccessfulLoginLogout.testSuccessfulLoinLogout()[pri:0, instance:tests.login.SuccessfulLoginLogout@253d9f73] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.login.SuccessfulLoginLogout -->
    </test> <!-- Demo Tests -->
  </suite> <!-- Demo Suite -->
</testng-results>
