<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S8LIHVD" failures="1" tests="1" name="tests.login.SuccessfulLoginLogoutTwoDrivers" time="18.137" errors="0" timestamp="2022-07-09T15:20:21 CEST" skipped="0">
  <testcase classname="tests.login.SuccessfulLoginLogoutTwoDrivers" name="testSuccessfulLoinLogoutTwoDrivers" time="18.137">
    <failure message="Nema!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Nema!
at org.testng.Assert.fail(Assert.java:110)
at tests.login.SuccessfulLoginLogoutTwoDrivers.testSuccessfulLoinLogoutTwoDrivers(SuccessfulLoginLogoutTwoDrivers.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testSuccessfulLoinLogoutTwoDrivers -->
  <system-out/>
</testsuite> <!-- tests.login.SuccessfulLoginLogoutTwoDrivers -->
